#!/bin/bash
make clean
tar cvzf etapa5.tgz hashtable.c hashtable.h scanner.l yacc.y astree.h astree.c main.c genco.c tac.c tac.h Makefile genco.c tac.c tac.h testeasm1.ling testeasm2.ling testeasm5.ling testeasm6.ling testeasm7.ling
#para o scp abaixo funcionar automaticamente, eh necessario utilizar
# autenticacao por chave do ssh
echo "Realizando o upload para o servidor html do inf..."
scp etapa5.tgz mcgjunior@html.inf.ufrgs.br:/home/grad/mcgjunior/public_html/
echo "Pronto!"
exit
