#!/bin/bash
make clean
tar cvzf etapa2.tgz hashtable.c hashtable.h scanner.l yacc.y main.c sample2.ling sample3.ling sample4.ling Makefile
#para o scp abaixo funcionar automaticamente, eh necessario utilizar
# autenticacao por chave do ssh
echo "Realizando o upload para o servidor html do inf..."
scp etapa2.tgz mcgjunior@html.inf.ufrgs.br:/home/grad/mcgjunior/public_html/
echo "Pronto!"
exit
