#!/bin/bash
make clean
tar cvzf etapa3.tgz hashtable.c hashtable.h scanner.l yacc.y main.c Makefile
#para o scp abaixo funcionar automaticamente, eh necessario utilizar
# autenticacao por chave do ssh
echo "Realizando o upload para o servidor html do inf..."
scp etapa3.tgz mcgjunior@html.inf.ufrgs.br:/home/grad/mcgjunior/public_html/
echo "Pronto!"
exit
